#KONSEP NAIVE BAYES

 * Langkah Perhitungan

###BINARY CLASSIFICATION



In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import *

In [8]:
df = pd.read_csv('/content/Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [17]:
#X = variabel independen berisi Age dan Estimated Salary
X = df.iloc[:,[2,3]].values

#Y = vaiabel dependen berisi Purchased
y = df.iloc[:,-1].values

In [38]:
print('X shape: ',X.shape)
print('y shape: ',y.shape)

X shape:  (400, 2)
y shape:  (400,)


In [25]:
print('X: \n', X[:5])
print('y: \n', y[:5])

X: 
 [[   19 19000]
 [   35 20000]
 [   26 43000]
 [   27 57000]
 [   19 76000]]
y: 
 [0 0 0 0 0]


###data split

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)

In [37]:
print('X_train shape: ',X_train.shape)
print('X_test shape: ',X_test.shape)
print('y_train shape: ',y_train.shape)
print('y_test shape: ',y_test.shape)

X_train shape:  (320, 2)
X_test shape:  (80, 2)
y_train shape:  (320,)
y_test shape:  (80,)


In [20]:
print('X_train : \n', X_train[:5])
print('y_train : \n', y_train[:5])

X_train : 
 [[    58 144000]
 [    59  83000]
 [    24  55000]
 [    26  35000]
 [    58  38000]]
y_train : 
 [1 0 0 0 1]


###classifier model

In [39]:
#traububg the NB model on the Training set
classifier_model_binary = GaussianNB()
classifier_model_binary.fit(X_train,y_train)

GaussianNB()

###predict test data

In [40]:
#predicting the test
y_pred = classifier_model_binary.predict(X_test)

In [61]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [74]:
for i,y in enumerate(y_pred[:5]):
  print(f'index {i} ==> {y}')

index 0 ==> 0
index 1 ==> 0
index 2 ==> 0
index 3 ==> 0
index 4 ==> 0


In [42]:
classifier_model_binary.predict_proba(X_test)

array([[0.89147043, 0.10852957],
       [0.84097849, 0.15902151],
       [0.85177346, 0.14822654],
       [0.91910807, 0.08089193],
       [0.89836193, 0.10163807],
       [0.95434022, 0.04565978],
       [0.90414431, 0.09585569],
       [0.03556946, 0.96443054],
       [0.98918806, 0.01081194],
       [0.50281633, 0.49718367],
       [0.95249262, 0.04750738],
       [0.96371556, 0.03628444],
       [0.85930139, 0.14069861],
       [0.7299999 , 0.2700001 ],
       [0.97431305, 0.02568695],
       [0.47994231, 0.52005769],
       [0.79297558, 0.20702442],
       [0.97847631, 0.02152369],
       [0.00422727, 0.99577273],
       [0.86019336, 0.13980664],
       [0.89871448, 0.10128552],
       [0.00500754, 0.99499246],
       [0.75594755, 0.24405245],
       [0.13376637, 0.86623363],
       [0.97909645, 0.02090355],
       [0.0047035 , 0.9952965 ],
       [0.9182418 , 0.0817582 ],
       [0.92764915, 0.07235085],
       [0.84823267, 0.15176733],
       [0.86172083, 0.13827917],
       [0.

In [55]:
def predict_one(age,salary):
  array_input = [[age,salary]]
  print(f'Probability : {classifier_model_binary.predict_proba(array_input)}')
  print(f'Predict : {classifier_model_binary.predict(array_input)}')

In [54]:
predict_one(30,87000)

Prob : [[0.89147043 0.10852957]]
Predict : [0]


In [71]:
#age = 18, salary = 210000
predict_one(18,210000)

Probability : [[3.38648471e-05 9.99966135e-01]]
Predict : [1]


###evaluate

In [72]:
print(classification_report(y_test,y_pred,zero_division=0))

              precision    recall  f1-score   support

           0       0.93      0.97      0.95        58
           1       0.90      0.82      0.86        22

    accuracy                           0.93        80
   macro avg       0.92      0.89      0.90        80
weighted avg       0.92      0.93      0.92        80



In [73]:
# making the confusion matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[56,  2],
       [ 4, 18]])

#contoh 2 - multiclass classification


In [77]:
#load dataset
df_train = pd.read_excel('/content/data_train.xlsx')
df_test = pd.read_csv('/content/data_test.csv')

In [78]:
df_train.head()

Jurusan  Matematika  Bahasa Inggris  Bahasa Indonesia  \
0      Matematika          92              86                88   
1      Matematika          90              86                85   
2  Sastra Inggris          82              87                92   
3      Matematika          93              82                85   
4  Sastra Inggris          86              85                88   

   Prestasi Siswa  Prestasi Sekolah  
0               1                 1  
1               1                 2  
2               2                 1  
3               1                 1  
4               1                 1

In [79]:
df_train.shape

(11, 6)

In [80]:
df_test.shape

(6, 6)

In [84]:
#split
X_train=df_train.drop(['Jurusan'],axis=1)
y_train = df_train['Jurusan']

X_test=df_test.drop(['Jurusan'],axis=1)
y_test = df_test['Jurusan']

In [86]:
X_train.head()

Matematika  Bahasa Inggris  Bahasa Indonesia  Prestasi Siswa  \
0          92              86                88               1   
1          90              86                85               1   
2          82              87                92               2   
3          93              82                85               1   
4          86              85                88               1   

   Prestasi Sekolah  
0                 1  
1                 2  
2                 1  
3                 1  
4                 1

In [87]:
y_train.head()

0        Matematika
1        Matematika
2    Sastra Inggris
3        Matematika
4    Sastra Inggris
Name: Jurusan, dtype: object

In [88]:
#create classifier model

classifier_model_multiclass = GaussianNB()
classifier_model_multiclass.fit(X_train,y_train)

GaussianNB()

In [91]:
#predict data
y_pred = classifier_model_multiclass.predict(X_test)

In [99]:
y_prob = classifier_model_multiclass.predict_proba(X_test)

In [100]:
y_prob

array([[9.84514205e-01, 1.54850655e-02, 7.29022414e-07],
       [9.99987686e-01, 0.00000000e+00, 1.23143756e-05],
       [2.29659067e-20, 9.99999810e-01, 1.90218794e-07],
       [2.13516750e-09, 9.99999996e-01, 1.89843957e-09],
       [2.44441357e-13, 6.49045316e-06, 9.99993510e-01],
       [1.39716921e-06, 9.99998424e-01, 1.78428054e-07]])

In [93]:
for i,y in enumerate(y_pred):
  print(f'prediction for index {i} --> {y}')

prediction for index 0 --> Matematika
prediction for index 1 --> Matematika
prediction for index 2 --> Sastra Indonesia
prediction for index 3 --> Sastra Indonesia
prediction for index 4 --> Sastra Inggris
prediction for index 5 --> Sastra Indonesia


In [102]:
print(classification_report(y_test,y_pred,zero_division=0))

                  precision    recall  f1-score   support

      Matematika       1.00      1.00      1.00         2
Sastra Indonesia       0.67      1.00      0.80         2
  Sastra Inggris       1.00      0.50      0.67         2

        accuracy                           0.83         6
       macro avg       0.89      0.83      0.82         6
    weighted avg       0.89      0.83      0.82         6



In [108]:
cm2 = confusion_matrix(y_test,y_pred)
cm2

array([[2, 0, 0],
       [0, 2, 0],
       [0, 1, 1]])

In [128]:
#predict multi class
#x = math, y = eng, z = id, a = prestasi siswa, b = prestasi sekolah
def predict_multi(x,y,z,a,b):
  array_input = [[x,y,z,a,b]]
  print(f'Probability : {classifier_model_multiclass.predict_proba(array_input)}')
  print(f'Predict : {classifier_model_multiclass.predict(array_input)}')

In [130]:
#x = math, y = eng, z = id, a = prestasi siswa, b = prestasi sekolah
predict_multi(92,82,85,1,1)

Probability : [[9.84514205e-01 1.54850655e-02 7.29022414e-07]]
Predict : ['Matematika']


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"
